### ISSUE TITLE
How to import?

### ISSUE THREAD

**Issue by szalapski** [gabfv/logitech-g-hub-settings-extractor#5]
Now that I've used this script to extract a JSON file per the README, how do I import the JSON file into a new installation of Logitech GHUB?  Could this info be added to the README?

![image](https://github.com/gabfv/logitech-g-hub-settings-extractor/assets/2723505/5424272d-6e69-436f-bf57-5eb406e2d85f)

**Comment by gabfv** [comment]
The script gives you instructions about what to do. In summary:
It extracts the JSON and open it into your editor (the default app per OS settings for json files, or the OS will let ask you what to open it with). It asks you to close Logitech G Hub then, once it's done, you can press Enter to continue.
You edit the file as you like. Then, you save the file and close the editor.
As soon as you close the editor, it automatically insert the modified JSON into Logitech G Hub sqlite db. When you open Logitech G Hub again, it should reflects the changes you've made.
I'll add it to the readme.
