### ISSUE TITLE
Possible to edit a backup settings.db?

### ISSUE THREAD

**Issue by mocmocmoc** [gabfv/logitech-g-hub-settings-extractor#6]
My Ghub profile was corrupted.
I have a backup "\AppData\Local\LGHUB" but Ghub keeps giving me error "Unable to save changes. An unknown error occured"
When I run this py script (with my backup db), I get error "Failed to read blob data from sqlite table database disk image is malformed"

Is there anyway to transfer my settings from my backup settings.db over to Ghub?

**Comment by gabfv** [comment]
Just to be clear, you've got multiple settings.db and the one named \AppData\Local\LGHUB\settings.db is currently corrupted? If you have backups of settings.db, it's possible to just rename the current settings.db to settings.db.old and rename a working backup to settings.db. Oh and do this while LGHUB is closed too!

However, I could look into adding a script parameter to specify an arbitrary "settings.db" file.

**Comment by mocmocmoc** [comment]
I went ahead and uninstalled LGHUB and went back to good ol Logitech Gaming Software. Never has I been this infuriated with a piece of software! Thanks a lot for your script anyway.
